# Generated by Django 3.2.7 on 2021-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211116_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=2, max_length=130),
            preserve_default=False,
        ),
    ]
